const GENESIS_GREETINGS = [
  "Good Morning",
  "Good Afternoon",
  "Good Evening",
  "Hey there",
  "Hello",
  "Hiya",
  "What's up",
  "Howdy",
  "Greetings",
  "Yo",
  "Sup",
  "Hey",
  "Hi",
  "Well hello there",
  "Look who's back",
  "Welcome back",
  "Nice to see you",
  "There you are",
  "Ready when you are",
  "Let's get to it",
  "Back again",
  "Good to have you",
  "Hey you",
  "Hello again",
  "What's cracking",
  "How's it going",
  "How are you",
  "What's new",
  "Long time no see",
  "Ahoy there",
  "Top of the morning",
  "Good day",
  "Hey hey",
  "Oh look, it's you",
  "The legend returns",
  "Here we go again",
  "Let's do this",
  "Alright, let's roll",
  "Fire away",
  "I'm all ears",
  "Shoot",
  "Hit me",
  "Go ahead",
  "What's on your mind",
  "Spill the tea",
  "Tell me everything",
  "I'm listening",
  "Your turn",
  "Lay it on me",
  "Don't hold back",
  "What's the sitch",
  "How's life",
  "What's happening",
  "What's the word",
  "What's the vibe",
  "How's tricks",
  "What's cookin",
  "How's your day",
  "What brings you here",
  "What's the plan",
  "Here to save the day",
  "The chosen one arrives",
  "The main character appears",
  "You again. I like it",
  "Look what the cat dragged in",
  "In the flesh at last",
  "The one and only",
  "How's my favourite human",
  "You just made my day",
  "CPU cycles at the ready",
  "Servers warmed up and waiting",
  "Boot sequence complete. You're up",
  "Initialising conversation... done",
  "Systems nominal. Query when ready",
  "Standing by",
  "Awaiting input",
  "Ready for duty",
  "At your service",
  "01001000 01100101 01101100 01101100 01101111",
  "Beep boop. You're here",
  "Error 404: patience not found. Let's go",
  "Loading your arrival animation... done",
  "Hello world. You're the main event",
  "Let's make some magic happen",
  "Another day, another query",
  "Round two. Or three. I lost count",
  "Alright, hit me with your best shot",
  "Let's get this bread",
  "You rang",
  "The suspense is killing me",
  "I was just thinking about you",
  "Well, well, well",
  "If it isn't my favourite user",
  "Here to break me again",
  "Ask away. I dare you",
  "I've been waiting",
  "Took you long enough",
  "Right on time",
  "Fashionably late as always",
  "Perfect timing",
  "You're just the person I wanted to see",
  "Let's make today productive",
  "Another day, another conversation",
  "Welcome to the party",
  "The gang's all here",
  "Alright, enough small talk",
  "Straight to business",
  "No time to waste",
  "Let's cut to the chase",
  "Efficiency mode: activated",
  "State your query",
  "Proceed when ready",
  "I'm optimised and ready",
  "Query away",
  "What's the mission",
  "Commands accepted",
  "Your wish is my command",
  "Speak, and I shall answer",
  "Enter your prompt",
  "Feed me a question",
  "What shall we explore today",
  "Where to next"
];

function getRandomGreeting() {
  return GENESIS_GREETINGS[Math.floor(Math.random() * GENESIS_GREETINGS.length)];
}
