const MORNING_GREETINGS = [
  "Good Morning",
  "Good Morning!",
  "Good Morning!!",
  "Good Morning~",
  "Good morning",
  "good morning!",
  "Morning!",
  "Morning!!",
  "Morning~",
  "Mornin'!",
  "Mornings!",
  "Good morn!",
  "G'morning!",
  "Rise and shine!",
  "Rise and shine!!",
  "Rise and shine, sleepyhead",
  "Rise and shine, sunshine",
  "Top of the morning!",
  "Top of the morning to you!",
  "Top of the mornin'!",
  "And a good morning to you",
  "A glorious morning indeed",
  "What a beautiful morning",
  "Beautiful morning, isn't it?",
  "Lovely morning we're having",
  "Fine morning this is",
  "Bright and early, I see",
  "The early bird gets the worm",
  "Up and at 'em!",
  "Wakey wakey!",
  "Wakey wakey, eggs and bakey",
  "Time to seize the day",
  "The day is young",
  "Another fresh morning",
  "Fresh morning, fresh start",
  "New day, new opportunities",
  "Sun's up, let's go",
  "The sun is shining",
  "Morning has broken",
  "Greetings at dawn",
  "A new dawn awaits",
  "Daybreak is here",
  "The early morning beckons",
  "Morning light is upon us",
  "Good day to you",
  "Good day!",
  "A splendid good day",
  "Good day, friend",
  "Here comes the sun",
  "Morning glory!",
  "Morning person alert!",
  "You're up early",
  "Early riser, huh?",
  "Some of us are awake",
  "The morning belongs to you",
  "Your morning starts now",
  "Let's start this morning right",
  "Buenos días",
  "Buenos días!",
  "Bonjour!",
  "Bonjour",
  "Guten Morgen!",
  "Guten Morgen",
  "Buongiorno!",
  "Buongiorno",
  "Bom dia!",
  "Bom dia",
  "Goedemorgen",
  "Goedemorgen!",
  "Kalimera",
  "Kalimera!",
  "Dobré ráno",
  "Dzień dobry",
  "Dzień dobry!",
  "Jó reggelt",
  "Jó reggelt!",
  "Hyvää huomenta",
  "God morgen",
  "God morgon",
  "Labas rytas",
  "Tere hommikust",
  "Bună dimineața",
  "Dobro jutro",
  "Dobré ráno!",
  "Bore da",
  "Bore da!",
  "Maidin mhaith",
  "Subh prabhat",
  "Shubh sakal",
  "Suprabhatam",
  "Ohayou gozaimasu",
  "Zǎo shang hǎo",
  "Annyeonghaseyo",
  "Selamat pagi",
  "Chào buổi sáng",
  "Magandang umaga",
  "Sawasdee ton chao",
  "Vanakkam",
  "Namaskara",
  "Namaste",
  "Shu'khran",
  "Sabah al-khair",
  "Pozdravljen",
  "Grüezi wohl",
  "Buon giorno",
  "Good morrow",
  "Hail the morning",
  "The morn is fair",
  "Bright morning to you",
  "Good morning, beautiful",
  "Morning, gorgeous",
  "Morning, handsome",
  "Morning, sunshine",
  "Morning, star",
  "Morning, champ",
  "Morning, legend",
  "Morning, chief",
  "Morning, friend",
  "Morning, buddy",
  "Morning, pal",
  "Morning, comrade",
  "Morning, captain",
  "Morning, boss",
  "Morning, hero",
  "Morning, genius",
  "Good morning, my friend",
  "Good morning, dear one",
  "Good morning, lovely",
  "Good morning, wonderful you",
  "Good morning, bright eyes",
  "Good morning, early bird",
  "Good morning, eager beaver",
  "Awake already? Morning!",
  "Is it morning already?",
  "Coffee's ready, are you?",
  "I hope you had a good rest",
  "Slept well, I hope",
  "Ready to conquer the day?",
  "The day awaits your greatness",
  "Today is full of promise",
  "This morning feels special",
  "You look well-rested",
  "A fresh start to a fresh day",
  "Let's brew some ideas",
  "Caffeinated and ready?",
  "Morning clarity is a gift",
  "Dawn chorus is singing",
  "The rooster crowed for you",
  "First light, first class",
  "Sunbeams and good vibes",
  "Morning dew on the grass",
  "The world is waking up",
  "You beat the sunrise",
  "Morning routines are overrated",
  "You made it to morning",
  "Congratulations on waking up",
  "Waking up is the first win",
  "Morning victory lap",
  "You're killing the morning game",
  "Another chance to shine",
  "The morning is yours for the taking",
  "Rays of light for rays of brilliance",
  "Let the morning inspire you",
  "Golden hour for golden ideas",
  "The world looks better in the morning",
  "Everything feels possible this morning",
  "A morning person's delight",
  "Even the birds are cheering",
  "Crack of dawn, crack of jokes",
  "Morning toast to you",
  "The kettle's on, let's chat",
  "Pour yourself a cup of ambition",
  "Good morning, world changer",
  "Morning, universe dominator",
  "Daylight savings? Who cares, it's morning",
  "No night owl here, it's morning!",
  "Morning stretches and deep breaths",
  "You're glowing with morning energy",
  "The sun came out for you",
  "Morning magic is real",
  "Start your engines, it's morning",
  "The morning train is leaving",
  "All aboard the morning express",
  "Clear skies and clear thinking",
  "Morning mindfulness activated",
  "Zen and the art of morning greetings",
  "Peaceful morning to you",
  "Calm and bright morning",
  "Tranquil morning vibes",
  "Morning serenity found",
  "Awake, alert, enthusiastic",
  "Morning motivation incoming",
  "Here's to a productive morning",
  "Let's make this morning count",
  "The morning is prime time",
  "Your best ideas come in the morning",
  "Creativity blooms in the morning",
  "The morning muse has arrived",
  "Good morning, creator",
  "Good morning, innovator",
  "Good morning, dreamer",
  "Good morning, doer",
  "Good morning, thinker"
];

const AFTERNOON_GREETINGS = [
  "Good Afternoon",
  "Good Afternoon!",
  "Good Afternoon!!",
  "Good Afternoon~",
  "Good afternoon",
  "good afternoon!",
  "Afternoon!",
  "Afternoon!!",
  "Afternoon~",
  "Good arvo!",
  "Top of the afternoon!",
  "Top of the afternoon to you",
  "A fine afternoon indeed",
  "Lovely afternoon we're having",
  "What a pleasant afternoon",
  "Beautiful afternoon, isn't it?",
  "Glorious afternoon sun",
  "The afternoon sun is warm",
  "Hope you're having a good day",
  "Halfway through the day!",
  "The day is in full swing",
  "Still going strong?",
  "Afternoon energy boost incoming",
  "You made it past noon",
  "Afternoon delight",
  "Afternoon greetings",
  "Good day for an afternoon chat",
  "The afternoon beckons",
  "Afternoon vibes are good",
  "Enjoying the afternoon?",
  "How's your afternoon going?",
  "Post-lunch clarity",
  "Refuelled and ready",
  "Hope lunch was good",
  "Afternoon slump? Not today",
  "Second wind time",
  "The afternoon belongs to you",
  "Keep the momentum going",
  "Don't slow down now",
  "Afternoon power hour",
  "Crushing it this afternoon",
  "Productivity peak time",
  "Afternoon excellence",
  "Good day to you!",
  "Good day",
  "A splendid afternoon to you",
  "Good afternoon greetings, friend",
  "Buenas tardes",
  "Buenas tardes!",
  "Bon après-midi!",
  "Bon après-midi",
  "Guten Nachmittag!",
  "Guten Nachmittag",
  "Buon pomeriggio!",
  "Buon pomeriggio",
  "Boa tarde!",
  "Boa tarde",
  "Goedemiddag",
  "Goedemiddag!",
  "Kaló apóyevma",
  "Dobré odpoledne",
  "Dzień dobry (po południu)",
  "Jó napot",
  "Jó napot!",
  "Hyvää iltapäivää",
  "God ettermiddag",
  "God eftermiddag",
  "Laba diena",
  "Tere päevast",
  "Bună după-amiaza",
  "Dober dan",
  "Bhaag pherno",
  "Ohayou gozaimasu (afternoon)",
  "Xià wǔ hǎo",
  "Annyeonghaseyo (afternoon)",
  "Selamat petang",
  "Chào buổi chiều",
  "Magandang hapon",
  "Sawasdee ton bai",
  "Vanakkam (afternoon)",
  "Namaskara (afternoon)",
  "Namaste (afternoon)",
  "Masaa al-khair",
  "Pozdravljen (afternoon)",
  "Grüezi wohl (afternoon)",
  "Afternoon, sunshine",
  "Afternoon, champ",
  "Afternoon, legend",
  "Afternoon, chief",
  "Afternoon, friend",
  "Afternoon, buddy",
  "Afternoon, pal",
  "Afternoon, boss",
  "Afternoon, captain",
  "Afternoon, hero",
  "Afternoon, superstar",
  "Afternoon, genius",
  "Afternoon, bright one",
  "Afternoon, my friend",
  "Afternoon, dear one",
  "Afternoon, lovely",
  "Afternoon, wonderful you",
  "Still at it? Respect",
  "Grinding through the afternoon",
  "The afternoon is your playground",
  "Sun's high, spirits higher",
  "Peak daylight, peak performance",
  "The sun is at its zenith",
  "No siesta, only fiesta",
  "Afternoon hustle",
  "Keep pushing forward",
  "You're doing great today",
  "Half day done, half to go",
  "The finish line is in sight",
  "Afternoon victories are sweet",
  "Let's make this afternoon count",
  "Afternoon ambition",
  "Driven through the afternoon",
  "Powered by lunch and ambition",
  "The afternoon grind is real",
  "You're unstoppable this afternoon",
  "Afternoon warrior",
  "Still shining bright",
  "Afternoon radiance",
  "Beaming through the afternoon",
  "Afternoon glow",
  "Productivity isn't slowing down",
  "The day's momentum is with you",
  "Charging through the afternoon",
  "Afternoon dynamo",
  "You're on fire this afternoon",
  "The afternoon is young",
  "Plenty of day left",
  "So much time, so much to do",
  "Afternoon opportunities await",
  "Make the most of this afternoon",
  "Afternoon adventures ahead",
  "Keep that afternoon energy",
  "The best part of the day continues",
  "Afternoon delight awaits",
  "Let the afternoon unfold",
  "Embrace the afternoon",
  "Savour the afternoon hours",
  "The afternoon breeze is nice",
  "Perfect afternoon for progress",
  "Afternoon synergy",
  "Collaboration hour is now",
  "Teamwork makes the afternoon work",
  "Afternoon check-in",
  "How are we feeling this afternoon?",
  "Afternoon morale boost",
  "You've got this afternoon in the bag",
  "Afternoon confidence is high",
  "You're nailing this afternoon",
  "Afternoon success story",
  "This afternoon is yours",
  "Command the afternoon",
  "Own this afternoon",
  "Conquer the afternoon",
  "Afternoon triumph incoming",
  "Victory by afternoon",
  "Afternoon achievements loading",
  "The afternoon is productive ground",
  "Rich afternoon harvest",
  "Reaping what you sowed this morning",
  "Afternoon fruits of labour",
  "Bountiful afternoon ahead",
  "The afternoon sun fuels your fire",
  "Golden afternoon hours",
  "Afternoon warmth for warm thoughts",
  "Cozy afternoon vibes",
  "Afternoon comfort zone",
  "Settled into the afternoon groove",
  "In the zone this afternoon",
  "Afternoon flow state",
  "Time flies in the afternoon",
  "Lost in the afternoon productivity",
  "Afternoon deep work session",
  "Deep focus this afternoon",
  "Afternoon concentration at its peak",
  "Zero distractions this afternoon",
  "Afternoon clarity",
  "Everything is clicking this afternoon",
  "Afternoon synergy activated",
  "Peak afternoon performance",
  "All systems go this afternoon",
  "Afternoon excellence mode",
  "Prime afternoon real estate",
  "This afternoon is premium content",
  "Afternoon edition of greatness"
];

const EVENING_GREETINGS = [
  "Good Evening",
  "Good Evening!",
  "Good Evening!!",
  "Good Evening~",
  "Good evening",
  "good evening!",
  "Evening!",
  "Evening!!",
  "Evening~",
  "Evenin'!",
  "Good eve!",
  "G'evening!",
  "Good night",
  "Good Night!",
  "Good night!!",
  "Night!",
  "Evening greetings",
  "A fine evening to you",
  "Lovely evening we're having",
  "What a pleasant evening",
  "Beautiful evening, isn't it?",
  "Glorious evening sky",
  "The evening is upon us",
  "As the sun sets",
  "Sunset is here",
  "Stars are coming out",
  "The evening beckons",
  "Evening vibes are setting in",
  "The day is winding down",
  "Hope you had a good day",
  "You made it through the day",
  "Evening relaxation mode",
  "Time to unwind",
  "The evening is yours to enjoy",
  "Wind down and breathe",
  "Evening calm",
  "The quiet of the evening",
  "Evening serenity",
  "Peaceful evening to you",
  "Evening tranquility",
  "The night is young",
  "Evening reflection time",
  "Rest and recharge",
  "You earned this evening",
  "Evening reward time",
  "The day's work is done",
  "Put your feet up",
  "Evening leisure time",
  "Savour the evening hours",
  "Evening bliss",
  "Buenas noches",
  "Buenas noches!",
  "Bonsoir!",
  "Bonsoir",
  "Guten Abend!",
  "Guten Abend",
  "Buona sera!",
  "Buona sera",
  "Boa noite!",
  "Boa noite",
  "Goedenavond",
  "Goedenavond!",
  "Kalispéra",
  "Kalispéra!",
  "Dobrý večer",
  "Dobry wieczór",
  "Dobry wieczór!",
  "Jó estét",
  "Jó estét!",
  "Hyvää iltaa",
  "God kveld",
  "God kväll",
  "Labas vakaras",
  "Tere õhtust",
  "Bună seara",
  "Dober večer",
  "Noswaith dda",
  "Tráthnóna maith",
  "Shubh sandhya",
  "Shubh ratri",
  "Konbanwa",
  "Wǎn shàng hǎo",
  "Annyeonghaseyo (evening)",
  "Selamat malam",
  "Chào buổi tối",
  "Magandang gabi",
  "Sawasdee ton yen",
  "Vanakkam (evening)",
  "Namaskara (evening)",
  "Masa al-khair",
  "Pozdravljen (evening)",
  "Grüezi wohl (evening)",
  "Evening, sunshine",
  "Evening, champ",
  "Evening, legend",
  "Evening, chief",
  "Evening, friend",
  "Evening, buddy",
  "Evening, pal",
  "Evening, boss",
  "Evening, captain",
  "Evening, hero",
  "Evening, superstar",
  "Evening, genius",
  "Evening, bright one",
  "Evening, my friend",
  "Evening, dear one",
  "Evening, lovely",
  "Evening, wonderful you",
  "The stars are aligning",
  "Evening magic is real",
  "The moon is rising",
  "Nightfall brings peace",
  "Dusk till dawn, you're awesome",
  "Twilight greetings",
  "The golden hour is here",
  "Evening glow",
  "Sunset colours and good vibes",
  "Day turned to night beautifully",
  "The evening air is crisp",
  "Perfect evening for a chat",
  "Night owl mode activated",
  "Evening thoughts are deeper",
  "The world quiets down",
  "Evening stillness",
  "Still waters run deep at night",
  "The evening is a blank canvas",
  "Evening dreams begin",
  "Night-time wisdom",
  "Evening introspection",
  "Look at the stars with me",
  "Evening constellations",
  "Night sky thoughts",
  "The evening is full of wonder",
  "Cosmic evening greetings",
  "Under the evening sky",
  "Evening musings",
  "The day's story ends here",
  "Close the day with grace",
  "Evening gratitude",
  "Thankful for this evening",
  "Evening contentment",
  "The day was long, but you persevered",
  "You made it to evening victorious",
  "Evening champion",
  "Rest well, you've earned it",
  "Evening well-being",
  "Evening self-care time",
  "Take a moment to breathe",
  "Breathe in the evening air",
  "Let the evening soothe you",
  "Evening relaxation protocols engaged",
  "Chill mode: activated",
  "Evening slowdown is welcome",
  "The pace of evening is peaceful",
  "Slow down, the night is long",
  "Evening leisure at its finest",
  "Unwind and let go",
  "Evening serenity found",
  "Calm seas and good evenings",
  "The evening tide brings rest",
  "Smooth sailing into the night",
  "Evening harbour is safe",
  "Docked for the evening",
  "Anchored in the evening calm",
  "Evening harbour thoughts",
  "The day's voyage is complete",
  "Evening stories to tell",
  "Nightfall narratives",
  "Evening tales unfold",
  "The night is full of stories",
  "Evening chapter begins",
  "Turn the page to evening",
  "The evening is a novel",
  "Write your evening story",
  "Evening plot twist",
  "Drama-free evening ahead",
  "Peaceful evening programming",
  "Evening entertainment awaits",
  "Lights dim, conversations deepen",
  "Evening intimacy of thought",
  "Night whispers",
  "The evening speaks softly",
  "Listen to the evening",
  "Evening sounds are soothing",
  "Night noises and quiet joys",
  "The evening hums a tune",
  "A lullaby for the evening",
  "Evening melodies",
  "The symphony of the night",
  "Evening harmony",
  "Everything settles in the evening",
  "Balance found at dusk",
  "Evening equilibrium",
  "The scales tip toward night",
  "Evening equipoise",
  "Stillness in the evening air",
  "Zen evening moments",
  "Mindfulness in the evening",
  "Evening meditation begins",
  "Centred and calm this evening",
  "Evening grounding",
  "Rooted in the evening peace",
  "Evening presence",
  "Here, now, in the evening",
  "The present moment is evening",
  "Evening awareness",
  "Conscious of the evening beauty",
  "The evening holds space for you",
  "Evening embrace",
  "Wrapped in evening comfort",
  "The evening welcomes you home",
  "Evening hearth and home",
  "Cosy evening indoors",
  "Warm lights for warm nights",
  "Evening hygge",
  "Comfort and joy this evening",
  "Evening contentment found",
  "The evening is your sanctuary",
  "Your evening retreat awaits",
  "Evening personal time",
  "Me-time this evening",
  "Solo evening bliss",
  "Evening solitude is golden",
  "Quiet evening for a quiet soul",
  "The evening is your companion",
  "Companionable silence of the evening",
  "Evening camaraderie",
  "Shared evening silence",
  "Together in the evening stillness",
  "Evening connections deepen",
  "The night brings people together",
  "Evening togetherness",
  "Warmth of company this evening",
  "Evening bonds strengthen",
  "Laughter in the evening air",
  "Joyful evening moments",
  "Evening delight",
  "The evening is full of smiles",
  "Happiness finds you this evening",
  "Evening joy radiates",
  "Bright evening spirits",
  "Your energy glows this evening",
  "Evening radiance",
  "You light up the evening",
  "Evening star quality",
  "Shine on this evening",
  "The evening is brighter with you",
  "Your presence elevates the evening",
  "Evening charisma",
  "Charming evening indeed",
  "An evening well spent",
  "Time well used this evening",
  "Evening well-lived",
  "Quality evening moments",
  "The evening was made for this",
  "Purposeful evening hours",
  "Evening with intention",
  "Meaningful evening pursuits",
  "Deep evening conversations",
  "Evening exchange of ideas",
  "Thought-provoking evening",
  "The evening inspires reflection",
  "Contemplative evening hours",
  "Evening philosophy",
  "The night makes you think",
  "Deep evening thoughts",
  "Profound evening musings",
  "Evening wisdom shared",
  "The evening imparts knowledge",
  "Learn something new this evening",
  "Evening enlightenment",
  "The night teaches those who listen"
];

const GENERAL_GREETINGS = [
  "Hey there",
  "Hello",
  "Hiya",
  "What's up",
  "Howdy",
  "Greetings",
  "Yo",
  "Sup",
  "Hey",
  "Hi",
  "Well hello there",
  "Look who's back",
  "Welcome back",
  "Nice to see you",
  "There you are",
  "Ready when you are",
  "Let's get to it",
  "Back again",
  "Good to have you",
  "Hey you",
  "Hello again",
  "What's cracking",
  "How's it going",
  "How are you",
  "What's new",
  "Long time no see",
  "Ahoy there",
  "Hey hey",
  "Oh look, it's you",
  "The legend returns",
  "Here we go again",
  "Let's do this",
  "Alright, let's roll",
  "Fire away",
  "I'm all ears",
  "Shoot",
  "Hit me",
  "Go ahead",
  "What's on your mind",
  "Spill the tea",
  "Tell me everything",
  "I'm listening",
  "Your turn",
  "Lay it on me",
  "Don't hold back",
  "What's the sitch",
  "How's life",
  "What's happening",
  "What's the word",
  "What's the vibe",
  "How's tricks",
  "What's cookin",
  "How's your day",
  "What brings you here",
  "What's the plan",
  "Here to save the day",
  "The chosen one arrives",
  "The main character appears",
  "You again. I like it",
  "Look what the cat dragged in",
  "In the flesh at last",
  "The one and only",
  "How's my favourite human",
  "You just made my day",
  "CPU cycles at the ready",
  "Servers warmed up and waiting",
  "Boot sequence complete. You're up",
  "Initialising conversation... done",
  "Systems nominal. Query when ready",
  "Standing by",
  "Awaiting input",
  "Ready for duty",
  "At your service",
  "01001000 01100101 01101100 01101100 01101111",
  "Beep boop. You're here",
  "Error 404: patience not found. Let's go",
  "Loading your arrival animation... done",
  "Hello world. You're the main event",
  "Let's make some magic happen",
  "Another day, another query",
  "Round two. Or three. I lost count",
  "Alright, hit me with your best shot",
  "Let's get this bread",
  "You rang",
  "The suspense is killing me",
  "I was just thinking about you",
  "Well, well, well",
  "If it isn't my favourite user",
  "Here to break me again",
  "Ask away. I dare you",
  "I've been waiting",
  "Took you long enough",
  "Right on time",
  "Fashionably late as always",
  "Perfect timing",
  "You're just the person I wanted to see",
  "Let's make today productive",
  "Another day, another conversation",
  "Welcome to the party",
  "The gang's all here",
  "Alright, enough small talk",
  "Straight to business",
  "No time to waste",
  "Let's cut to the chase",
  "Efficiency mode: activated",
  "State your query",
  "Proceed when ready",
  "I'm optimised and ready",
  "Query away",
  "What's the mission",
  "Commands accepted",
  "Your wish is my command",
  "Speak, and I shall answer",
  "Enter your prompt",
  "Feed me a question",
  "What shall we explore today",
  "Where to next"
];

function getRandomGreeting() {
  const now = new Date();
  const hour = now.getHours();
  const month = now.getMonth();
  const day = now.getDate();

  // May 23rd, 2-3 PM (14:00-15:00): 10% chance of birthday greeting
  if (month === 4 && day === 23 && hour >= 14 && hour < 15 && Math.random() < 0.1) {
    return "Happy Birthday";
  }

  // Time-aware selection: morning, afternoon, or evening pool
  let pool;
  if (hour >= 0 && hour < 12) {
    pool = MORNING_GREETINGS;
  } else if (hour >= 12 && hour < 17) {
    pool = AFTERNOON_GREETINGS;
  } else {
    pool = EVENING_GREETINGS;
  }

  return pool[Math.floor(Math.random() * pool.length)];
}
