const MORNING_GREETINGS = [
  "Good morning! How can I help you today?",
  "Good morning! What can I do for you?",
  "Good morning! Ready to help with whatever you need.",
  "Good morning! How can I assist you this morning?",
  "Good morning! I'm here and ready to help.",
  "Good morning! What's on your mind today?",
  "Good morning! How can I brighten your morning?",
  "Good morning! What can we work on together?",
  "Good morning! I'm all yours. What do you need?",
  "Good morning! Let me know how I can help.",
  "Morning! How can I help you today?",
  "Morning! What can I assist you with?",
  "Morning! Ready when you are.",
  "Morning! I'm here to help. What do you need?",
  "Morning! What can I do for you this fine morning?",
  "Morning! How's it going? What can I help with?",
  "Morning! Let's make today productive. What do you need?",
  "Morning! I'm at your service. What's first?",
  "Morning! What are we working on today?",
  "Morning! How can I make your day easier?",
  "Good morning! It's a great day to get things done. How can I help?",
  "Good morning! I hope you're well. What can I do for you?",
  "Good morning! I'm ready whenever you are.",
  "Good morning! What would you like to explore today?",
  "Good morning! Let's tackle something together.",
  "Good morning! What's on the agenda?",
  "Good morning! I'm here to support you. What do you need?",
  "Good morning! How can I be most useful to you?",
  "Good morning! What's the first thing I can help with?",
  "Good morning! I'm excited to help you today.",
  "Good morning! What can we achieve together this morning?",
  "Good morning! I've got my thinking cap on. What's up?",
  "Good morning! What can I help you figure out?",
  "Good morning! How can I contribute to your day?",
  "Good morning! I'm here to make things easier for you.",
  "Good morning! What's the first task on your list?",
  "Good morning! I'm all ears. How can I assist?",
  "Good morning! Let's make some progress together.",
  "Good morning! How can I help you move forward?",
  "Good morning! What do you have in mind?",
  "Morning! It's a fresh start. How can I help?",
  "Morning! I'm ready to dive in. What do you need?",
  "Morning! I'm here for you. What's on your plate?",
  "Morning! How can I support you today?",
  "Morning! What's the plan? I'm ready.",
  "Morning! Let's get started. What can I do?",
  "Morning! I'm fully charged and ready to go.",
  "Morning! What would be most helpful right now?",
  "Morning! I'm here whenever you need me.",
  "Morning! How can I be of service today?",
  "Rise and shine! How can I help this morning?",
  "Rise and shine! What can I do for you?",
  "Good day! What can I help you with?",
  "Good day! How can I assist you today?",
  "Hey there! Good morning. How can I help?",
  "Hey there! What can I do for you this morning?",
  "Hello! Good morning. How can I assist you?",
  "Hello! What can I help you with today?",
  "Hi! Good morning. How can I be helpful?",
  "Hi there! How can I help you this morning?",
  "Hi there! What can I do for you today?",
  "Hi! What can I help you with this morning?",
  "Hey! Good morning. What's on your mind?",
  "Good morning to you! How can I help?",
  "A very good morning! What can I assist with?",
  "Good morning, friend! How can I help?",
  "Good morning! What can we figure out together?",
  "Good morning! How can I make your life easier?",
  "Good morning! I'm ready to help. What's the task?",
  "Good morning! I'm here to assist. What do you need?",
  "Good morning! What challenge can we solve today?",
  "Good morning! How can I help you make progress?",
  "Good morning! What's something I can help you with?",
  "Good morning! I'm here when you need a hand.",
  "Good morning! Let's get things moving. What first?",
  "Good morning! I'm ready to jump in. What's up?",
  "Good morning! What can I help you accomplish?",
  "Good morning! I'm here to make your day better.",
  "Good morning! What would you like to work on?",
  "Good morning! How can I add value to your morning?",
  "Good morning! I'm at your disposal. What's next?",
  "Good morning! What can I help you think through?",
  "Good morning! How can I help you start your day right?",
  "Good morning! What's the most important thing I can help with?",
  "Good morning! What can we create together today?",
  "Good morning! How can I best support you this morning?",
  "Good morning! I'm listening. What do you need?",
  "Good morning! What interesting thing can we explore?",
  "Good morning! How can I help you achieve your goals?",
  "Good morning! I'm ready to help. Where should we start?",
  "Good morning! What can I take off your plate?",
  "Good morning! How can I help you be more productive?",
  "Good morning! I'm here to lend a hand. What's up?",
  "Good morning! Let's make this morning count. How can I help?",
  "Good morning! What's the plan for today? I'm ready.",
  "Good morning! How can I help you make today great?",
  "Good morning! What would you like to accomplish?",
  "Good morning! I'm here to help you succeed.",
  "Good morning! How can I help you today? I'm all ears.",
  "Good morning! What can I do to help you shine?",
  "Good morning! Let's work on something great together.",
  "Good morning! I'm here and eager to help.",
  "Good morning! What's the first thing on your mind?",
  "Good morning! How can I assist you in being awesome today?",
  "Good morning! I've got your back. What do you need?",
  "Good morning! What can I help you discover today?",
  "Good morning! I'm here to make things happen. What's first?",
  "Good morning! How can I help you this beautiful morning?",
  "Good morning! Let's make some magic happen. What's on your mind?",
  "Good morning! I'm here to help you thrive today.",
  "Good morning! What's the first thing I can assist with?",
  "Good morning! I'm ready and waiting. What can I do?",
  "Good morning! How can I help you seize the day?",
  "Good morning! What can I help you build or solve?",
  "Good morning! I'm here to help you do your best work.",
  "Good morning! What's on your mind? I'm listening.",
  "Good morning! How can I be of help this morning?",
  "Good morning! I'm here to assist with anything you need.",
  "Good morning! What would make this morning productive for you?",
  "Good morning! Let's get down to business. What's first?",
  "Good morning! How can I help you make progress today?",
  "Good morning! What can I do to support you?",
  "Good morning! I'm ready to help. What's our first task?",
  "Good morning! Let's keep the momentum going together.",
  "Good morning! How can I help you tackle today's challenges?",
  "Good morning! I'm here to make your life easier.",
  "Good morning! What are you hoping to achieve?",
  "Good morning! How can I help you focus today?",
  "Good morning! I'm at your service. What do you need?",
  "Good morning! What excellent thing are we doing today?",
  "Good morning! How can I help you make today meaningful?",
  "Good morning! I'm here to help you grow and learn.",
  "Good morning! What can I help you with right now?",
  "Good morning! I'm here to make your day smoother.",
  "Good morning! How can I assist you in reaching your potential?",
  "Good morning! What's on your mind? I'm here to help.",
  "Good morning! Let's get creative. What can I help with?",
  "Good morning! I'm ready for anything. What do you need?",
  "Good morning! How can I help you be your best today?",
  "Good morning! What can I help you think about?",
  "Good morning! I'm here to help you every step of the way.",
  "Good morning! What challenge are we solving today?",
  "Good morning! How can I help you make today successful?",
  "Good morning! I'm here to be your assistant. What's up?",
  "Good morning! How can I help you make the most of today?",
  "Good morning! Let's do something awesome. What's first?",
  "Good morning! What can I help you learn or create?",
  "Good morning! I'm here to help you move forward.",
  "Good morning! What's something I can help you improve?",
  "Good morning! I'm here to help you accomplish great things.",
  "Good morning! How can I help you today? Let's get started.",
  "Good morning! What's our goal for today?",
  "Good morning! I'm here to help you stay on track.",
  "Good morning! What can I help you organize or plan?",
  "Good morning! I'm here to help you succeed today.",
  "Good morning! How can I help you be productive and happy?",
  "Good morning! What's the best thing I can help you with?",
  "Good morning! I'm ready to assist. Where do we start?",
  "Good morning! How can I help you make today amazing?",
  "Good morning! I'm here to help you achieve your dreams.",
  "Good morning! What can we explore together today?",
  "Good morning! I'm here to help you find answers.",
  "Good morning! How can I help you solve problems today?",
  "Good morning! I'm here to help you build something great.",
  "Good morning! What's the most exciting thing I can help with?",
  "Good morning! I'm here to help you make decisions.",
  "Good morning! How can I help you learn something new?",
  "Good morning! I'm here to help you stay inspired.",
  "Good morning! What can I help you understand better?",
  "Good morning! I'm here to help you grow.",
  "Good morning! How can I help you make an impact today?",
  "Good morning! I'm here to help you think bigger.",
  "Good morning! What can I help you simplify today?",
  "Good morning! I'm here to help you find clarity.",
  "Good morning! How can I help you make progress on your goals?",
  "Good morning! I'm here to help you work smarter.",
  "Good morning! What can I help you achieve this morning?",
  "Good morning! I'm here to help you make the most of your time.",
  "Good morning! I'm ready to help. Let's make it happen."
];

const AFTERNOON_GREETINGS = [
  "Good afternoon! How can I help you today?",
  "Good afternoon! What can I do for you?",
  "Good afternoon! How can I assist you this afternoon?",
  "Good afternoon! I'm here and ready to help.",
  "Good afternoon! What's on your mind?",
  "Good afternoon! How's your day going? What can I help with?",
  "Good afternoon! What can we work on together?",
  "Good afternoon! I'm all yours. What do you need?",
  "Good afternoon! Let me know how I can help.",
  "Good afternoon! I hope you're having a great day so far.",
  "Afternoon! How can I help you today?",
  "Afternoon! What can I assist you with?",
  "Afternoon! Ready when you are.",
  "Afternoon! I'm here to help. What do you need?",
  "Afternoon! What can I do for you this fine afternoon?",
  "Afternoon! How's it going? What can I help with?",
  "Afternoon! Let's keep the momentum going. What do you need?",
  "Afternoon! I'm at your service. What's up?",
  "Afternoon! What are we working on?",
  "Afternoon! How can I make your afternoon productive?",
  "Good afternoon! I hope you're doing well. How can I help?",
  "Good afternoon! I'm ready whenever you are.",
  "Good afternoon! What would you like to explore today?",
  "Good afternoon! Let's tackle something together.",
  "Good afternoon! What's the agenda for the rest of the day?",
  "Good afternoon! I'm here to support you. What do you need?",
  "Good afternoon! How can I be most useful to you right now?",
  "Good afternoon! What can we accomplish together?",
  "Good afternoon! I'm excited to help you this afternoon.",
  "Good afternoon! What can we achieve together?",
  "Good afternoon! I've got my thinking cap on. What's up?",
  "Good afternoon! How can I help you figure things out?",
  "Good afternoon! I'm here to make things easier for you.",
  "Good afternoon! What's the next task on your list?",
  "Good afternoon! I'm all ears. How can I assist?",
  "Good afternoon! Let's make some progress together.",
  "Good afternoon! How can I help you move forward?",
  "Good afternoon! What do you have in mind?",
  "Good afternoon! What can I help you finish today?",
  "Good afternoon! I'm here to help you cross things off your list.",
  "Good afternoon! How can I help you stay productive?",
  "Good afternoon! What's the most important thing I can help with?",
  "Good afternoon! Let's keep the energy going. How can I help?",
  "Good afternoon! I'm here to help you push through.",
  "Good afternoon! What can we solve together this afternoon?",
  "Afternoon! It's a great time to get things done. How can I help?",
  "Afternoon! I'm here to help you power through.",
  "Afternoon! How can I support you this afternoon?",
  "Afternoon! What's the plan? I'm ready.",
  "Afternoon! Let's get to it. What can I do?",
  "Afternoon! I'm fully focused and ready to help.",
  "Afternoon! What would be most helpful for you right now?",
  "Afternoon! I'm here whenever you need me.",
  "Afternoon! How can I be of service this afternoon?",
  "Afternoon! How's your day shaping up?",
  "Afternoon! What can I help you wrap up?",
  "Afternoon! Let's make the rest of the day count.",
  "Afternoon! What's something I can help you with?",
  "Afternoon! I'm here to help you finish strong.",
  "Afternoon! How can I help you make progress?",
  "Good day! How can I help you this afternoon?",
  "Good day! What can I assist you with?",
  "Hey there! Good afternoon. How can I help?",
  "Hey there! What can I do for you this afternoon?",
  "Hello! Good afternoon. How can I assist you?",
  "Hello! What can I help you with this afternoon?",
  "Hi! Good afternoon. How can I be helpful?",
  "Hi there! How can I help you this afternoon?",
  "Hi! What can I help you with this afternoon?",
  "Hey! Good afternoon. What's on your mind?",
  "Good afternoon to you! How can I help?",
  "Hi there! What can I assist you with this afternoon?",
  "A very good afternoon! What can I assist with?",
  "Good afternoon, friend! How can I help?",
  "Good afternoon! What can we figure out together?",
  "Good afternoon! How can I make your day better?",
  "Good afternoon! I'm ready to help. What's the task?",
  "Good afternoon! I'm here to assist. What do you need?",
  "Good afternoon! What challenge can we solve?",
  "Good afternoon! How can I help you keep going?",
  "Good afternoon! What's something I can do for you?",
  "Good afternoon! I'm here when you need a hand.",
  "Good afternoon! Let's get things moving. What's next?",
  "Good afternoon! I'm ready to jump in. What's up?",
  "Good afternoon! What can I help you accomplish?",
  "Good afternoon! I'm here to make your afternoon great.",
  "Good afternoon! What would you like to work on?",
  "Good afternoon! How can I add value to your afternoon?",
  "Good afternoon! I'm at your disposal. What's next?",
  "Good afternoon! What can I help you think through?",
  "Good afternoon! How can I help you make the most of today?",
  "Good afternoon! What's the most important thing I can assist with?",
  "Good afternoon! What can we create together?",
  "Good afternoon! How can I best support you right now?",
  "Good afternoon! I'm here to help you move forward today.",
  "Good afternoon! I'm listening. What do you need?",
  "Good afternoon! What interesting thing can we dive into?",
  "Good afternoon! How can I help you achieve your goals?",
  "Good afternoon! I'm ready to help. Where should we focus?",
  "Good afternoon! What can I take off your plate?",
  "Good afternoon! How can I help you be more productive?",
  "Good afternoon! I'm here to lend a hand. What's up?",
  "Good afternoon! Let's make this afternoon count. How can I help?",
  "Good afternoon! How can I help you make today successful?",
  "Good afternoon! What would you like to accomplish?",
  "Good afternoon! I'm here to help you succeed.",
  "Good afternoon! How can I help you today? I'm all ears.",
  "Good afternoon! Let's work on something great together.",
  "Good afternoon! I'm here and eager to help.",
  "Good afternoon! How can I help you stay focused?",
  "Good afternoon! I'm here to help you finish the day strong.",
  "Good afternoon! What's the most pressing thing I can help with?",
  "Good afternoon! I've got your back. What do you need?",
  "Good afternoon! Let's solve something interesting.",
  "Good afternoon! I'm here to make things happen. What's first?",
  "Good afternoon! How can I help you this fine afternoon?",
  "Good afternoon! What's on your mind? I'm ready to help.",
  "Good afternoon! I'm here to help you thrive.",
  "Good afternoon! What's the next big thing we can tackle?",
  "Good afternoon! I'm ready and waiting. What can I do?",
  "Good afternoon! How can I help you make progress today?",
  "Good afternoon! What can I help you build or solve?",
  "Good afternoon! I'm here to help you do your best work.",
  "Good afternoon! What's on your mind? I'm listening.",
  "Good afternoon! How can I be of help this afternoon?",
  "Good afternoon! I'm here to assist with anything you need.",
  "Good afternoon! What would make this afternoon productive for you?",
  "Good afternoon! Let's get down to business. What's first?",
  "Good afternoon! How can I help you wrap up your day?",
  "Good afternoon! What can I do to support you?",
  "Good afternoon! I'm ready to help. What's our next move?",
  "Good afternoon! Let's stay productive this afternoon.",
  "Good afternoon! How can I help you tackle today's challenges?",
  "Good afternoon! I'm here to make your life easier.",
  "Good afternoon! What are you hoping to achieve?",
  "Good afternoon! How can I help you stay on track?",
  "Good afternoon! I'm at your service. What do you need?",
  "Good afternoon! What excellent thing are we doing today?",
  "Good afternoon! How can I help you make today meaningful?",
  "Good afternoon! I'm here to help you grow and learn.",
  "Good afternoon! What can I help you with right now?",
  "Good afternoon! I'm here to make your afternoon smoother.",
  "Good afternoon! How can I assist you in reaching your goals?",
  "Good afternoon! What's on your mind? I'm here to help.",
  "Good afternoon! Let's get creative. What can I help with?",
  "Good afternoon! I'm ready for anything. What do you need?",
  "Good afternoon! I'm here to help you every step of the way.",
  "Good afternoon! What challenge are we solving today?",
  "Good afternoon! How can I help you make this day great?",
  "Good afternoon! I'm here to be your assistant. What's up?",
  "Good afternoon! How can I help you make the most of your time?",
  "Good afternoon! Let's do something awesome. What's first?",
  "Good afternoon! What can I help you learn or create?",
  "Good afternoon! I'm here to help you move forward.",
  "Good afternoon! What's something I can help you improve?",
  "Good afternoon! I'm here to help you accomplish great things.",
  "Good afternoon! How can I help you today? Let's keep going.",
  "Good afternoon! What's the priority for the rest of the day?",
  "Good afternoon! I'm here to help you stay energized.",
  "Good afternoon! What can I help you organize or plan?",
  "Good afternoon! I'm here to help you finish what you started.",
  "Good afternoon! How can I help you be productive this afternoon?",
  "Good afternoon! What's the best thing I can help you with?",
  "Good afternoon! I'm ready to assist. Where do we focus?",
  "Good afternoon! How can I help you make today amazing?",
  "Good afternoon! I'm here to help you achieve your dreams.",
  "Good afternoon! What can we explore together this afternoon?",
  "Good afternoon! I'm here to help you find answers.",
  "Good afternoon! How can I help you solve problems today?",
  "Good afternoon! I'm here to help you build something great.",
  "Good afternoon! What's the most exciting thing I can help with?",
  "Good afternoon! I'm here to help you make decisions.",
  "Good afternoon! How can I help you learn something new?",
  "Good afternoon! I'm here to help you stay inspired.",
  "Good afternoon! What can I help you understand better?",
  "Good afternoon! I'm here to help you grow.",
  "Good afternoon! How can I help you make an impact today?",
  "Good afternoon! I'm here to help you think bigger.",
  "Good afternoon! What can I help you simplify?",
  "Good afternoon! I'm here to help you find clarity.",
  "Good afternoon! How can I help you make progress?",
  "Good afternoon! I'm here to help you work smarter."
];

const EVENING_GREETINGS = [
  "Good evening! How can I help you today?",
  "Good evening! What can I do for you?",
  "Good evening! How can I assist you this evening?",
  "Good evening! I'm here and ready to help.",
  "Good evening! What's on your mind?",
  "Good evening! How was your day? What can I help with?",
  "Good evening! What can we work on together?",
  "Good evening! I'm all yours. What do you need?",
  "Good evening! Let me know how I can help.",
  "Good evening! I hope you had a good day.",
  "Evening! How can I help you tonight?",
  "Evening! What can I assist you with?",
  "Evening! Ready when you are.",
  "Evening! I'm here to help. What do you need?",
  "Evening! What can I do for you this evening?",
  "Evening! How's it going? What can I help with?",
  "Evening! I hope you're winding down nicely.",
  "Evening! I'm at your service. What's up?",
  "Evening! What are we working on?",
  "Evening! How can I help you relax and be productive?",
  "Good evening! I hope you're doing well. How can I help?",
  "Good evening! I'm ready whenever you are.",
  "Good evening! What would you like to explore tonight?",
  "Good evening! Let's work on something together.",
  "Good evening! What's on the agenda for tonight?",
  "Good evening! I'm here to support you. What do you need?",
  "Good evening! How can I be most useful to you?",
  "Good evening! What can we accomplish this evening?",
  "Good evening! I'm here to help you wind down or power through.",
  "Good evening! What can we figure out together?",
  "Good evening! I've got my thinking cap on. What's up?",
  "Good evening! How can I help you think things through?",
  "Good evening! I'm here to make things easier for you.",
  "Good evening! I'm all ears. How can I assist?",
  "Good evening! Let's make some progress together.",
  "Good evening! How can I help you move forward?",
  "Good evening! What do you have in mind?",
  "Good evening! What can I help you finish up?",
  "Good evening! I'm here to help you tie up loose ends.",
  "Good evening! How can I help you reflect or plan?",
  "Good evening! What's on your mind this evening?",
  "Good evening! Let's keep the momentum going. How can I help?",
  "Good evening! I'm here to help you make the most of tonight.",
  "Good evening! What can we solve together this evening?",
  "Evening! It's a great time to get things done. How can I help?",
  "Evening! I'm here to help you finish strong.",
  "Evening! How can I support you this evening?",
  "Evening! What's the plan? I'm ready.",
  "Evening! Let's get to it. What can I do?",
  "Evening! I'm fully focused and ready to help.",
  "Evening! What would be most helpful for you right now?",
  "Evening! I'm here whenever you need me.",
  "Evening! How can I be of service this evening?",
  "Evening! How's your evening going so far?",
  "Evening! What can I help you with tonight?",
  "Evening! Let's make the most of this evening.",
  "Evening! What's something I can help you explore?",
  "Evening! I'm here to help you unwind or get things done.",
  "Evening! How can I help you make progress tonight?",
  "Good evening! What can I help you learn or discover?",
  "Good evening! How can I assist you tonight?",
  "Hey there! Good evening. How can I help?",
  "Hey there! What can I do for you this evening?",
  "Hello! Good evening. How can I assist you?",
  "Hello! What can I help you with tonight?",
  "Hi! Good evening. How can I be helpful?",
  "Hi there! How can I help you this evening?",
  "Hi there! What can I do for you tonight?",
  "Hi! What can I help you with this evening?",
  "Hey! Good evening. What's on your mind?",
  "Good evening to you! How can I help?",
  "A very good evening! What can I assist with?",
  "Good evening, friend! How can I help?",
  "Good evening! What can we explore together?",
  "Good evening! How can I make your evening better?",
  "Good evening! I'm ready to help. What's the task?",
  "Good evening! I'm here to assist. What do you need?",
  "Good evening! What challenge can we solve?",
  "Good evening! How can I help you enjoy your evening?",
  "Good evening! What's something I can do for you?",
  "Good evening! I'm here when you need a hand.",
  "Good evening! Let's get things moving. What's next?",
  "Good evening! I'm ready to jump in. What's up?",
  "Good evening! What can I help you accomplish?",
  "Good evening! I'm here to make your evening great.",
  "Good evening! What would you like to work on?",
  "Good evening! How can I add value to your evening?",
  "Good evening! I'm at your disposal. What's next?",
  "Good evening! What can I help you think through?",
  "Good evening! How can I help you make the most of tonight?",
  "Good evening! What's the most important thing I can assist with?",
  "Good evening! What can we create together tonight?",
  "Good evening! How can I best support you right now?",
  "Good evening! I'm here to help you finish strong tonight.",
  "Good evening! I'm listening. What do you need?",
  "Good evening! What interesting thing can we dive into?",
  "Good evening! How can I help you achieve your goals?",
  "Good evening! I'm ready to help. Where should we focus?",
  "Good evening! What can I take off your plate?",
  "Good evening! How can I help you be productive this evening?",
  "Good evening! I'm here to lend a hand. What's up?",
  "Good evening! Let's make this evening count. How can I help?",
  "Good evening! How can I help you make today meaningful?",
  "Good evening! What would you like to accomplish?",
  "Good evening! I'm here to help you succeed.",
  "Good evening! How can I help you tonight? I'm all ears.",
  "Good evening! Let's work on something great together.",
  "Good evening! I'm here and eager to help.",
  "Good evening! How can I help you reflect on today?",
  "Good evening! I'm here to help you prepare for tomorrow.",
  "Good evening! What's the most pressing thing I can help with?",
  "Good evening! I've got your back. What do you need?",
  "Good evening! Let's solve something interesting.",
  "Good evening! I'm here to make things happen. What's first?",
  "Good evening! How can I help you this evening?",
  "Good evening! What's on your mind? I'm ready to help.",
  "Good evening! I'm here to help you unwind or get ahead.",
  "Good evening! What can we tackle together tonight?",
  "Good evening! I'm ready and waiting. What can I do?",
  "Good evening! How can I help you end the day well?",
  "Good evening! What can I help you build or solve?",
  "Good evening! I'm here to help you do your best work.",
  "Good evening! What's on your mind? I'm listening.",
  "Good evening! How can I be of help tonight?",
  "Good evening! I'm here to assist with anything you need.",
  "Good evening! What would make this evening productive for you?",
  "Good evening! Let's get down to business. What's first?",
  "Good evening! How can I help you wrap up your day?",
  "Good evening! What can I do to support you?",
  "Good evening! I'm ready to help. What's our next move?",
  "Good evening! Here to help you tie up loose ends.",
  "Good evening! How can I help you tackle any challenges?",
  "Good evening! I'm here to make your life easier.",
  "Good evening! What are you hoping to achieve?",
  "Good evening! How can I help you stay on track?",
  "Good evening! I'm at your service. What do you need?",
  "Good evening! What excellent thing are we doing tonight?",
  "Good evening! How can I help you make tonight meaningful?",
  "Good evening! I'm here to help you grow and learn.",
  "Good evening! What can I help you with right now?",
  "Good evening! I'm here to make your evening smoother.",
  "Good evening! How can I assist you in reaching your goals?",
  "Good evening! What's on your mind? I'm here to help.",
  "Good evening! Let's get creative. What can I help with?",
  "Good evening! I'm ready for anything. What do you need?",
  "Good evening! I'm here to help you every step of the way.",
  "Good evening! What challenge are we solving tonight?",
  "Good evening! How can I help you make this evening great?",
  "Good evening! I'm here to be your assistant. What's up?",
  "Good evening! How can I help you make the most of your time?",
  "Good evening! Let's do something awesome. What's first?",
  "Good evening! What can I help you learn or create?",
  "Good evening! I'm here to help you move forward.",
  "Good evening! What's something I can help you improve?",
  "Good evening! I'm here to help you accomplish great things.",
  "Good evening! How can I help you tonight? Let's get started.",
  "Good evening! What's the priority for tonight?",
  "Good evening! I'm here to help you stay focused.",
  "Good evening! What can I help you organize or plan?",
  "Good evening! I'm here to help you finish what you started.",
  "Good evening! How can I help you be productive tonight?",
  "Good evening! What's the best thing I can help you with?",
  "Good evening! I'm ready to assist. Where do we focus?",
  "Good evening! How can I help you make tonight amazing?",
  "Good evening! I'm here to help you achieve your dreams.",
  "Good evening! What can we explore together tonight?",
  "Good evening! I'm here to help you find answers.",
  "Good evening! How can I help you solve problems tonight?",
  "Good evening! I'm here to help you build something great.",
  "Good evening! What's the most exciting thing I can help with?",
  "Good evening! I'm here to help you make decisions.",
  "Good evening! How can I help you learn something new?",
  "Good evening! I'm here to help you stay inspired.",
  "Good evening! What can I help you understand better?",
  "Good evening! I'm here to help you grow.",
  "Good evening! How can I help you make an impact?",
  "Good evening! I'm here to help you think bigger.",
  "Good evening! What can I help you simplify tonight?",
  "Good evening! I'm here to help you find clarity.",
  "Good evening! How can I help you make progress?",
  "Good evening! I'm here to help you rest and recharge too."
];

const GENERAL_GREETINGS = [
  "Hi there! How can I help you today?",
  "Hello! What can I do for you?",
  "Hi! How can I assist you today?",
  "Hey there! What can I help you with?",
  "Hello! I'm here to help. What do you need?",
  "Hi! What's on your mind today?",
  "Hey! How can I help you today?",
  "Hi there! I'm ready to assist. What's up?",
  "Hello! What can we work on together?",
  "Hi! How can I be useful to you?",
  "Hey there! I'm here whenever you need me.",
  "Hello! Let me know what you need help with.",
  "Hi! I'm all ears. What can I do for you?",
  "Hello there! How can I help you?",
  "Hi there! What can I assist you with today?",
  "Hey! What's on your mind? I'm here to help.",
  "Hello! What would you like to explore today?",
  "Hi! How can I make your life easier?",
  "Hey there! I'm ready to help. What's first?",
  "Hello! What challenge can I help you solve?",
  "Hi there! I'm here to support you. What do you need?",
  "Hey! Let's get started. How can I help?",
  "Hello! What can I help you accomplish today?",
  "Hi! I'm here to help you succeed. What's up?",
  "Hey there! What interesting thing can we dive into?",
  "Hello! How can I help you make progress?",
  "Hi! What can I help you figure out today?",
  "Hey! I'm here to lend a hand. What do you need?",
  "Hello there! What can I do for you today?",
  "Hi there! Let's work on something great together.",
  "Hello! What's the first thing I can help with?",
  "Hi! I'm at your service. What's on your mind?",
  "Hey! How can I add value to your day?",
  "Hello! I'm here and ready to assist.",
  "Hi there! What can we create together today?",
  "Hey there! I'm all yours. What do you need?",
  "Hello! How can I help you think things through?",
  "Hi! What can I help you learn or discover?",
  "Hey! I'm here to help you achieve your goals.",
  "Hello! What problem can we solve together?",
  "Hi there! How can I support you today?",
  "Hey there! I'm ready to dive in. What's up?",
  "Hello! What's the most important thing I can help with?",
  "Hi! I'm here to make things happen. What do you need?",
  "Hey! Let's make some magic happen. How can I help?",
  "Hello! How can I help you be your best today?",
  "Hi there! What's on your agenda?",
  "Hey there! I'm here to help you move forward.",
  "Hello! What can I take off your plate today?",
  "Hi! I'm here to make your day better. What's up?",
  "Hey! What can we build or solve together?",
  "Hello! I'm ready to assist with anything you need.",
  "Hi there! What's the first thing on your mind?",
  "Hey there! I'm here to help you grow and learn.",
  "Hello! How can I help you make today great?",
  "Hi! Let's get down to business. What's first?",
  "Hey! I'm here to help you stay inspired.",
  "Hello! What can I help you organize or plan?",
  "Hi there! I'm fully focused and ready to help.",
  "Hey there! What can we accomplish together?",
  "Hello! I'm here to help you do your best work.",
  "Hi! How can I help you think bigger today?",
  "Hey! I'm here to help you find clarity.",
  "Hello! What interesting challenge can we tackle?",
  "Hi there! I'm here to help you create something great.",
  "Hey there! How can I be most useful to you?",
  "Hello! What can I help you explore today?",
  "Hi! I'm here and eager to dive in. What's up?",
  "Hey! How can I help you make progress on your goals?",
  "Hello! What's the next step I can help with?",
  "Hi there! I'm ready to help. Where should we start?",
  "Hey there! I'm here to help you work smarter.",
  "Hello! What can I help you understand better?",
  "Hi! How can I assist you in reaching your potential?",
  "Hey! I'm here to help you make an impact.",
  "Hello! What can we figure out together today?",
  "Hi there! I'm here to help you stay on track.",
  "Hey there! How can I help you be productive today?",
  "Hello! I'm here to support you every step of the way.",
  "Hi! What's the most exciting thing I can help with?",
  "Hey! I'm here to help you make decisions.",
  "Hello! What can I help you simplify today?",
  "Hi there! I'm here to help you find answers.",
  "Hey there! How can I help you make today meaningful?",
  "Hello! I'm here to help you achieve great things.",
  "Hi! What can I help you with right now?",
  "Hey! I'm here to help you stay focused and inspired.",
  "Hello! What can we discover together today?",
  "Hi there! I'm here to help you succeed.",
  "Hey there! How can I help you make the most of today?",
  "Hello! I'm here and ready to go. What's the plan?",
  "Hi! What can I help you reflect on today?",
  "Hey! I'm here to help you prepare for what's next.",
  "Hello! How can I help you tie up loose ends?",
  "Hi there! What can I help you finish today?",
  "Hey there! I'm here to help you wrap things up.",
  "Hello! How can I help you make this day count?",
  "Hi! Let's do something awesome together. What's first?",
  "Hey! I'm here to help you think outside the box.",
  "Hello! What's something new I can help you learn?",
  "Hi there! I'm here to help you stay curious.",
  "Hey there! How can I help you turn ideas into reality?",
  "Hello! I'm here to help you bring your vision to life.",
  "Hi! What can I help you plan or brainstorm?",
  "Hey! I'm here to help you solve the puzzles of the day.",
  "Hello! What can I help you communicate or express?",
  "Hi there! I'm here to help you see things from a new angle.",
  "Hey there! How can I help you grow your skills?",
  "Hello! I'm here to help you navigate complexity.",
  "Hi! What can I help you automate or simplify?",
  "Hey! I'm here to help you make informed decisions.",
  "Hello! What can I help you research or analyze?",
  "Hi there! I'm here to help you think strategically.",
  "Hey there! How can I help you unlock your potential?",
  "Hello! I'm here to help you connect the dots.",
  "Hi! What can I help you write or create?",
  "Hey! I'm here to help you debug or troubleshoot.",
  "Hello! What can I help you design or envision?",
  "Hi there! I'm here to help you optimize your workflow.",
  "Hey there! How can I help you understand something deeply?",
  "Hello! I'm here to help you break down complex problems.",
  "Hi! What can I help you test or validate?",
  "Hey! I'm here to help you improve your process.",
  "Hello! What can I help you explore or investigate?",
  "Hi there! I'm here to help you make progress step by step.",
  "Hey there! How can I help you think critically?",
  "Hello! I'm here to help you generate new ideas.",
  "Hi! What can I help you implement or build?",
  "Hey! I'm here to help you refine your thinking.",
  "Hello! What can I help you learn from today's experience?",
  "Hi there! I'm here to help you plan your next move.",
  "Hey there! How can I help you prioritize your tasks?",
  "Hello! I'm here to help you find the right approach.",
  "Hi! What can I help you understand more clearly?",
  "Hey! I'm here to help you turn challenges into opportunities.",
  "Hello! How can I help you make better choices?",
  "Hi there! I'm here to help you develop new perspectives.",
  "Hey there! What can I help you explore creatively?",
  "Hello! I'm here to help you analyze and improve.",
  "Hi! What can I help you organize or structure?",
  "Hey! I'm here to help you identify patterns and insights.",
  "Hello! How can I help you make sense of complexity?",
  "Hi there! I'm here to help you build confidence in your ideas.",
  "Hey there! What can I help you refine or polish?",
  "Hello! I'm here to help you expand your horizons.",
  "Hi! What can I help you prototype or test?",
  "Hey! I'm here to help you learn from data and feedback.",
  "Hello! How can I help you think more creatively?",
  "Hi there! I'm here to help you communicate your ideas.",
  "Hey there! What can I help you deconstruct or understand?",
  "Hello! I'm here to help you develop a clear plan.",
  "Hi! What can I help you question or challenge?",
  "Hey! I'm here to help you validate your assumptions.",
  "Hello! How can I help you see the bigger picture?",
  "Hi there! I'm here to help you focus on what matters.",
  "Hey there! What can I help you appreciate or celebrate?",
  "Hello! I'm here to help you learn from mistakes.",
  "Hi! What can I help you look forward to?",
  "Hey! I'm here to help you build momentum."
];

function getRandomGreeting() {
  const now = new Date();
  const hour = now.getHours();
  const month = now.getMonth();
  const day = now.getDate();

  if (month === 4 && day === 23 && hour >= 14 && hour < 15 && Math.random() < 0.1) {
    return "Happy Birthday";
  }

  let pool;
  if (hour >= 0 && hour < 12) {
    pool = MORNING_GREETINGS;
  } else if (hour >= 12 && hour < 17) {
    pool = AFTERNOON_GREETINGS;
  } else {
    pool = EVENING_GREETINGS;
  }

  return pool[Math.floor(Math.random() * pool.length)];
}