/**
 * Genesis-AI: Text Authentication Module (TXTAuth)
 * Detects AI-generated text using signature matching and linguistic heuristics.
 */

(function() {
    // 1. The "Secret" Watermarks & Signatures
    // These patterns are often embedded or characteristic of AI outputs.
    const AI_WATERMARKS = [
        "As an AI language model",
        "I cannot fulfill this request",
        "I am a large language model",
        "I do not have personal opinions",
        "I don't have feelings",
        "My knowledge cutoff",
        "I am an artificial intelligence",
        "generated by OpenAI",
        "I cannot browse the internet",
        "I cannot access real-time information",
        "As a machine learning model",
        "I am designed to be helpful",
        "Is there anything else I can help you with?",
        "I apologize, but I cannot",
        "It is important to note that",
        "regenerate response"
    ];

    // 2. Linguistic Heuristics ("Other Checks")
    // AI tends to use certain transition words and formal structures more frequently.
    const AI_INDICATORS = [
        { pattern: /however, it is important/i, score: 3 },
        { pattern: /in conclusion,/i, score: 2 },
        { pattern: /furthermore,/i, score: 2 },
        { pattern: /moreover,/i, score: 2 },
        { pattern: /it is worth noting/i, score: 3 },
        { pattern: /comprehensive/i, score: 1 },
        { pattern: /crucial/i, score: 1 },
        { pattern: /nuanced/i, score: 1 },
        { pattern: /delve/i, score: 1 },
        { pattern: /tapestry/i, score: 1 },
        { pattern: /testament/i, score: 1 },
        { pattern: /underscores/i, score: 1 }
    ];

    const HUMAN_INDICATORS = [
        { pattern: /\bi\b/, score: 2 }, // Lowercase 'i'
        { pattern: /\b(lol|lmao|idk|tbh|im|dont|cant)\b/i, score: 3 }, // Slang/Contractions without apostrophe
        { pattern: /[!]{2,}/, score: 1 }, // Multiple exclamation marks
        { pattern: /\.{2,}/, score: 1 } // Ellipsis usage (informal)
    ];

    window.authenticateText = function(text) {
        return new Promise((resolve) => {
            if (!text || typeof text !== 'string' || text.trim().length === 0) {
                resolve("Error: No text provided for analysis.");
                return;
            }

            const cleanText = text.trim();
            
            // --- CHECK 1: WATERMARKS (Immediate Fail) ---
            for (const mark of AI_WATERMARKS) {
                if (cleanText.includes(mark)) {
                    resolve(`Analysis Result: AI-Generated\n\nReason: Detected explicit AI watermark phrase: "${mark}".\nConfidence: 99.9%`);
                    return;
                }
            }

            // --- CHECK 2: LINGUISTIC ANALYSIS (The "Other Checks") ---
            let aiScore = 0;
            let humanScore = 0;

            AI_INDICATORS.forEach(item => { if (item.pattern.test(cleanText)) aiScore += item.score; });
            HUMAN_INDICATORS.forEach(item => { if (item.pattern.test(cleanText)) humanScore += item.score; });

            const totalScore = aiScore - humanScore;
            let verdict = totalScore >= 3 ? "Likely AI-Generated" : 
                          totalScore >= 1 ? "Possibly AI-Generated" : 
                          totalScore <= -2 ? "Likely Human-Written" : "Inconclusive";

            resolve(`Analysis Result: ${verdict}\n\nAI Pattern Score: ${aiScore}\nHuman Pattern Score: ${humanScore}`);
        });
    };
})();

console.log("TXTAuth Module Loaded");
