/**
 * Genesis-AI: Text Authentication Module (TXTAuth) v2.1
 * Advanced detection using entropy, burstiness, and linguistic weighting.
 */

(function() {
    const AI_WATERMARKS = [
        "As an AI language model", "I cannot fulfill this request",
        "I am a large language model", "I do not have personal opinions",
        "My knowledge cutoff", "I am an artificial intelligence",
        "generated by OpenAI", "As a machine learning model",
        "I apologize, but I cannot", "It is important to note that",
        "delve into the", "a testament to", "the tapestry of"
    ];

    const AI_INDICATORS = [
        { pattern: /however, it is (important|crucial|essential)/i, score: 3 },
        { pattern: /in conclusion,/i, score: 2 },
        { pattern: /furthermore,/i, score: 2 },
        { pattern: /moreover,/i, score: 2 },
        { pattern: /it is worth noting/i, score: 3 },
        { pattern: /\b(comprehensive|nuanced|underscores|pivotal|multifaceted)\b/i, score: 1.5 }
    ];

    const HUMAN_INDICATORS = [
        { pattern: /\b(i|me|my)\b/g, score: 0.5 },
        { pattern: /\b(lol|lmao|idk|tbh|im|dont|cant|wanna|gonna)\b/i, score: 3 },
        { pattern: /[!]{2,}/, score: 2 },
        { pattern: /\.{2,}/, score: 1.5 },
        { pattern: /\b(anyway|so|like|basically)\b/i, score: 1 }
    ];

    const getEntropy = (str) => {
        const len = str.length;
        const freq = Array.from(str).reduce((acc, char) => {
            acc[char] = (acc[char] || 0) + 1;
            return acc;
        }, {});
        return Object.values(freq).reduce((sum, f) => {
            const p = f / len;
            return sum - p * Math.log2(p);
        }, 0);
    };

    const getBurstiness = (text) => {
        const sentences = text.split(/[.!?]+/).filter(s => s.trim().length > 0);
        if (sentences.length < 3) return { variance: 0, avg: 0 };
        const lengths = sentences.map(s => s.trim().split(/\s+/).length);
        const avg = lengths.reduce((a, b) => a + b) / lengths.length;
        const variance = lengths.reduce((a, b) => a + Math.pow(b - avg, 2), 0) / lengths.length;
        return { variance, avg };
    };

    window.authenticateText = function(text) {
        return new Promise((resolve) => {
            if (!text || text.trim().split(/\s+/).length < 20) {
                resolve("Error: Text too short for reliable analysis (min 20 words).");
                return;
            }

            const cleanText = text.trim();
            let aiScore = 0;
            let humanScore = 0;

            // 1. Watermark Check
            for (const mark of AI_WATERMARKS) {
                if (cleanText.includes(mark)) {
                    aiScore += 10;
                }
            }

            // 2. Pattern Matching
            AI_INDICATORS.forEach(item => { 
                const matches = cleanText.match(item.pattern);
                if (matches) aiScore += item.score * matches.length; 
            });
            HUMAN_INDICATORS.forEach(item => { 
                const matches = cleanText.match(item.pattern);
                if (matches) humanScore += item.score * matches.length; 
            });

            // 3. Structural Analysis
            const { variance } = getBurstiness(cleanText);
            const entropy = getEntropy(cleanText);

            if (variance < 8) aiScore += 4; // Robotic consistency
            if (variance > 25) humanScore += 3; // Natural variety
            if (entropy < 3.8) aiScore += 2; // Low complexity

            const totalScore = aiScore - humanScore;
            let verdict = totalScore > 7 ? "Highly Likely AI" : 
                          totalScore > 3 ? "Likely AI" : 
                          totalScore < -3 ? "Likely Human" : "Inconclusive";

            resolve({
                verdict,
                confidence: Math.min(Math.abs(totalScore) * 10, 99),
                metrics: { aiScore, humanScore, variance: variance.toFixed(2), entropy: entropy.toFixed(2) }
            });
        });
    };
})();
